rubyide/vscode-ruby

- package.json
- src/ruby.ts
If no arguments are passed in the option file `args.args` is unset and with the ... operator the value `undefined` is appended to the array. Spawn then rewrites this to the string `"undefined"`.
This change extends with an empty array instead if `args.args` is undefined.
> Fix undef argv and options typo

- syntaxes/ruby.tmLanguage
Highlighting syntax changed from .other to .language for symbols between v0.10.x and 1.0.
> rename .other.symbol to .language.symbol

- package.json
- readme.md
- ruby.js
Adds auto indent for opening elements requiring an `end` element, but only when they are the first word on the line.
de-indenting is not included because VSCode implements it only after the line, but an `end` tag should be at the same indentation as the opening tag. The `end` tag will need to be manually un-tabbed.
> Auto indent

- package.json
- readme.md
- ruby.js
- src/main.ts
I wonder that you will have an interesting.
> Add completion feature

- readme.md
Update the readme.md debugging links with current wiki page urls.
> Tweak wiki links for debugging

- readme.md
Only a README change, should not affect:
I think VS Code 1.4.0 switched the extensions into a side panel, now you cannot install an extension with one command, this explains the 2 step process. Fixes #53
> Update readme.md fixes #53

- language-configuration.json
- package.json
- ruby.js
Auto Closing Pairs only works if the language settings are in a file - more specifically, it doesn't work when loading settings with `setLanguageConfiguration` which is flat out crazy. This is currently causing indenting to fail.
This is totally my fault because I suggested that those setting be placed in the langConfig passed to `setLanguageConfiguration`.
Version bumped in `package.json` ready for deployment.
> Auto Closing Pairs causes settings load to fail

- package.json
- syntaxes/ruby.tmLanguage
Adds support for recognizing [.jbuilder](https://github.com/rails/jbuilder) files as Ruby automatically.
> Recognize .jbuilder file extension as Ruby

- .vscode/launch.json
- ruby.js
Add `decreaseIndentPattern` to have keywords like `end` get correct auto unindent.
This is the code change in our side while seems VS Code doesn't take `decreaseIndentPattern` correctly as Atom or Sublime does, we'll wait to see when VS Code gets a fix for it.
> add decreaseIndentPattern

- src/ruby.ts
This updates the parsing logic to handle XML data that contains non-element nodes.  I discovered this issue while doing some research on #95 and learned that `sketchup-ruby-debugger` outputs newlines which result in unexpected text nodes causing `vscode-ruby` to fail.  This PR simply skips over any non-element nodes.
---
> RubyProcess: Fix XML parsing.

- lint/lib/linter.js
- lint/lib/linters/RuboCop.js
- lint/lintCollection.js
- ruby.js
Expected:
In rails project, `spec/foo/foobar_spec.rb` should not be claimed by cop `Metrics/BlockLength`, because it is [excluded by default config](https://github.com/bbatsov/rubocop/blob/aeaab434ac32e33cc9e22839f2079e905590fce6/config/default.yml#L1162)
Actual without this PR:
Warning is shown for BlockLength.
----
By rubocop's design, exclude paths in default config is relative to working dir, not to the dir contains `.rubocop.yml`.
https://github.com/bbatsov/rubocop/issues/3145
So this PR use workspace.rootPath for cwd.
----
> Use rootDir for cwd to obey relative exclude path in rubocop

- locate/locate.js
- package.json
- ruby.js
Now it supports Cmd+Shift+O / Cmd+T symbol list..!
> Add document and workspace symbol provider

- lint/lib/linters/Ruby.js
- readme.md
I use non-Ascii characters frequently, and since Ruby 2.0 source files are handled as UTF8 by default. `ruby -wc` however does not handle that correctly unless you pass a extra argument for forcing the character set (`-Ku`).
Because I don't know if people rely on the old behavior, this PR adds a flag for the RubyWC linter for enabling Unicode handling, disabled by default.
> Add config to set Unicode handling on `ruby -wc` linting

- .travis.yml
- package.json
- src/ruby.ts
> Add support for custom ports to the Ruby debugger.

- src/main.ts
Improves the handling when files referenced in the stacktrace aren't available where vscode is running. Addresses two issues that were causing the debugger to throw an exception (and so fail to provide the call stack and current position) when debugging a rails app within a docker container:
- The rails app ran within the `/app` directory in the container, so files such as `/usr/local/lib/gems/railties-3.0.20/lib/rails/application.rb` weren't being filtered out by the check on line 259, which resulted in an exception when attempting to read the file (as the file only exists within the docker container)
- One stack frame reported by rdebug-ide had a line number of 0, which caused an exception when trying to get the line from the array (on line 275).
This PR changes the logic so that …
> Make stacktrace handling of missing files more robust

- package.json
In `ruby.lint` settings, the `ruby` linter can have not only `boolean` but also `object` value, for example, the readme says:
```js
"ruby.lint": {
"ruby": {
"unicode": true //Runs ruby -wc -Ku
},
```
However, since current property of `ruby` linter only accepts `boolean`, setting an object as `ruby` linter configuration complains that there exists a type mismatch.
So I have changed the property setting of `ruby` linter to accept either `boolean` or `object`.
> Fix type of ruby linter property

- locate/locate.js
- package.json
- ruby.js
This PR fixes "too many open files" error caused by calling non-blocking functions in forEach()..!
Also implements cool progress indicator in status bar 😎
> Completely fix too many open files issue by using queue

- package.json
This pull request is to add `"filenames"` entry to `"languages"` section. By using this configuration, some file without extension such as `Gemfile` or `Puppetfile` is recognized as ruby.  
Also fix  #162 
> Add filenames to package.json

- snippets/erb.json
- snippets/ruby.json
Trying to remove these errors in VS Code 1.13+ due to wrongly typed snippet variables.
```
...vscode/extensions/rebornix.ruby-0.12.1]: The "each"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
```
> Fix snippet syntax errors

- snippets/ruby.json
First of all, I really appreciate the work that's gone into this extension. It's helped me out a ton. I see that Rake support is in the roadmap, but had use for this snippet, so I thought it may help to have it already sorted out.
Since it's just a simple JSON addition, I didn't sort out the build process but I did test the snippet in my own VSCode (v. 1.15). Thanks for all you do, and no worries if this doesn't get merged.
Make sure these boxes are checked before submitting your PR -- thanks in advance! (Sorry!)
> Add a rake task snippet

- package.json
- src/debugger/ruby.ts
This adds an includes fields in the ruby tasks, which are passed as `-I` to rdebug-ide.
> define the 'includes' field in the debug configuration

- src/task/rake.ts
> Fixed typo in error message when failed to find rake tasks

- .travis.yml
- language-configuration-erb.json
Some times I need to program more ruby code in `erb`, i.e:
```
<%
set_meta_tags title: "title",
og: {
title: "my title",
description: "some description"
},
image: "image path"
%>
```
vscode-ruby [default comment](https://github.com/rubyide/vscode-ruby/blob/master/language-configuration-erb.json#L3) will create `<%# %>`, may look like
```
<%
set_meta_tags title: "title",
og: {
title: "my title",
description: "some description"
},
<%# image: "image path" %>
%>
```
but the ideal comment should be 
```
<%
set_meta_tags title: "title",
og: {
title: "my title",
description: "some description"
},
%
```
so I adjust the comment configuration
> adjust erb comment configuration

- src/ruby.ts
Refer the following pull request and the issues linked in it:
https://github.com/Microsoft/vscode/pull/40049
@rebornix 
This PR seems to come into a bit of conflict with #223, should make a decision on which one we're going to use.
Here's the thing:
1. If `case` doesn't indent the next line and `when` doesn't unindent, the indentation will be ok only while we're adding `when` clauses, but will break when we use `else` and/or `end` (because these 2  do unindent). The result of using the changes made in #233 would be this:
```rb
case thing
when 2 then true
when 4 then false
else nil
end
```
2. With this PR the `case` statement does indent the next line but any of `when`, `else` and `end` will unindent leading to a desired output:
```rb
case thing
when 2 then true
when 4 then false
else nil …
```
> Update indent pattern

- package.json
Adds a `firstLine` definition so files with a ruby shebang are detected correctly
> Fix shebang detection

- src/ruby.ts
This updates the entry regex to handle the uses cases outlined in #234. The original regex did not correctly match on patterns like `def foo(params = {})` or `bar = if ...`.
This fixes #234.
> Fix getEntry regex to handle additional cases

- .travis.yml
- appveyor.yml
This PR does a few things:
* Adds ruby 2.4 to the build matrix in appveyor
* Syncs the rubies tested on Travis with appveyor
* Upgrades the tested node version to the new LTS release
* Fixes the build to make sure everything is run through `nvm`
> Fix Travis

- src/lint/lib/linter.js
This PR introduces support for interpolating the `workspaceRoot` into the linter path and running the linter via bundler. This should resolve #188 and #187.
The linter path will be resolved in the following order:
1. If a path is set on the linter, that will be used. `${workspaceRoot}` will be interpolated.
2. It will attempt to find the linter name via bundler
3. It will call the linter name (eg the linter is installed globally)
This also makes a change to the directory in which the linter is executed. Before it would execute in the project root and fall back to the target file's working directory. Now it does the opposite. This was a requirement to support #188. This has the potential to break people who have set the linter path to be relative to the workspace root. The upgrade path …
> Add workspaceRoot and bundler support

- package.json
- syntaxes/gemfile.cson.json
Gemfiles are parsed like ruby but have should support different
highlighting (eg the keyword gem should highlight in a Gemfile but
probably not in normal Ruby). This grammar enables this difference.
> Add support for Gemfile grammar

- src/ruby.ts
Couldn't figure out how to handle indentation in some edge cases so I thought I would try to port Atoms indent pattern to VSCode since I've never had issues when working in Atom.
Well for some reason just copy pasting their indent pattern didn't work so I spent a couple of hours understanding and tweaking it. So this is the result.
Now indentation handles all these cases as expected:
---
I won't bother explaining what exactly wasn't working and is working with this PR cause there is a lot of stuff. Well one thing would be that it wouldn't indent after:
```rb
describe "#some_method" do
```
because it saw a `#` inside the string and thought it was a comment.
---
Point is. Everything works as expected now …
> Indent patterns (again)

- language-configuration-erb.json
- package.json
This PR reverts the changes done in #224 so that commenting in ERB files again works correctly (resolving #255). In addition, it specifies the `embeddedLanguages` key on the ERB language grammar definition that allows VSCode to assign a different language scope for embedded languages. This PR specifies that Ruby, CSS, and JS can be embedded in ERB.
> Fixes to ERB comments

- package.json
- readme.md
- src/ruby.ts
This PR adds the `ruby.intellisense` configuration to allow method selection for go to/peek definition similar to `ruby.codeCompletion`. Valid options are `solargraph`, `rubyLocate`, and `none`.
> Add `ruby.intellisense` configuration option

- package-lock.json
- package.json
- src/lint/lib/linter.js
- src/lint/lintCollection.ts
- src/lint/lintConfig.ts
- src/ruby.ts
The pathToBundler and useBundler settings allow to control whether
and how linters will be using bundler. Not setting useBundler retains
the current auto-detection behavior, but setting it to either true
or false will avoid the call to bundler altogether.
> add settings to control bundler usage for linters

- scripts/meta.function-call.ruby.json
- scripts/update-grammar.js
- scripts/variable.other.ruby.json
- syntaxes/ruby.cson.json
The original syntax highlighting was based on an "optimistic" syntax highlighting grammar. This change allows us to continue to use the upstream Atom grammar but will insert the correct grammar scopes to still support the optimistic highlighting.
See [here](https://github.com/rubyide/vscode-ruby/issues/251#issuecomment-363093172) for information on what these scopes mean and why.
Note that I could not discover a way to support `constant.other.symbol` and `constant.language.symbol` at the same time. This means Ruby symbols will be highlighted the same as core language constants (like `nil`). In reality this is probably ok as most themes with explicit support appear to map the same color to both types.
Before:
After:
> Modify upstream grammar to support optimistic syntax. Resolves #251.

- package.json
- readme.md
- src/ruby.ts
I've been having this issue https://github.com/rubyide/vscode-ruby/issues/252 where the linters run after every keypress and cause significant input lag.
This PR makes the linters only run when typing has finished, instead of after each letter.
Before:
After:
EDIT: Updated to include a configuration option for the delay.
> Debounce linting to prevent running on every keypress

- package.json
- src/debugger/main.ts
- src/debugger/ruby.ts
This functionality is mapped to CTRL+F5. When one uses it,
the debugger is instructed to run the program without the
debugger.
To achieve this, the commit adds a pathToRuby configuration
parameter that allows to set which ruby should be used.
> support running launch entries without debugging

- src/format/RuboCop.ts
- src/format/rubyFormat.ts
Better error handling & messages when running RuboCop formatting. Centralized handling of opts in that class. Since this file changed so much I also ran prettier.
> Better error handling & messages when running RuboCop formatting

- package.json
- readme.md
- src/format/rubyFormat.ts
Added support for ruby.format, defaults to false (no formatting). Set it to 'rubocop' to enable rubocop formatting. Fixes #295.
> Added support for ruby.format, defaults to false (no formatting).

- package.json
- readme.md
- src/ruby.ts
* The solargraph dependency is removed.
* `ruby.codeCompletion` and `ruby.intellisense` use `false` to disable rcodetools and rubyLocate respectively.
* When rubyLocate is disabled, the `ruby.reloadProject` command displays informative messages.
> Remove solargraph dependency and update codeCompletion and intellisense options

- .prettierrc
- .vscode/extensions.json
- .vscode/settings.json
- package-lock.json
- package.json
- tslint.json
This change adds tslint & prettier as dev dependencies and recommends the vscode extensions as well. Using tslint will increase the quality of our work with very little dev cost. Prettier will auto-format our js and ts files on save. This sidesteps all problems related to code formatting, since prettier will just take care of it for us.
There are no code changes in this PR. Once this is merged, we should go ahead and run tslint and prettier across the entire source tree as a single PR. Otherwise we'll suffer through piecemeal diffs for subsequent PRs.
If we agree that this is a step we'd like to take, please read the proposed `.prettierrc` below. You can see the full list of options here:
https://prettier.io/docs/en/options.html
Personally I don't care very much about the specific …
> Add tslint/prettier for linting/formatting.

- .vscode/settings.json
- package.json
- src/providers/completion.ts
- src/providers/formatter.ts
- src/providers/highlight.ts
- src/providers/intellisense.ts
- src/providers/linters.ts
- src/ruby.ts
First pass at cleaning up the code. This pass just basically moves most of the providers into their own files for better organization. `ruby.ts` got a bit of cleanup via the linter/prettier but nothing substantial.
> Code Cleanup - first pass

- readme.md
Debase 0.2.2 was released a few days ago and supports ruby 2.5.1
> Update Readme.md to fix version of debase gem

- readme.md
This is in response to numerous issues requesting help with gem install issues. I've wrestled with some of these issues myself.
Perhaps this will help. I included a reference to solargraph in the docs, even though it's going away as a dependency. I expect there will still be people looking for assistance here.
> add some readme hints about gem dependencies

- src/format/rubyFormat.ts
- src/providers/completion.ts
- src/providers/formatter.ts
- src/providers/highlight.ts
- src/providers/intellisense.ts
- src/ruby.ts
- src/task/rake.ts
In preparation for [Visual Studio Live Share](https://aka.ms/vsls) adding support for "guests" to receive remote language services for Ruby, this PR makes the following changes:
1. Updates the current `DocumentSelector` to be limited to `file` and `untitled` (unsaved) files.
1. Prevents the linter from running on workspaces that don't appear to have a root path (which a Live Share/virtual file system wouldn't). The task and intellisense providers already did this, so I made some minor refactorings to gate them all behind the same check.
With these changes, when someone has the Ruby extension installed, and joins a Live Share session (where files use the `vsls:` scheme), their language services will be entirely derived from the remote/host side, which provides a more accurate and …
> [Discussion] [Live Share] Restricting language services to local files

- readme.md
It feels they aren't needed now that you get the right versions with a plain gem install, and it also makes the readme more easily be outdated if keep them here.
Here are the current versions I got when running `gem install`:
```shell
$ gem install ruby-debug-ide
Fetching: ruby-debug-ide-0.6.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed ruby-debug-ide-0.6.1
Parsing documentation for ruby-debug-ide-0.6.1
Installing ri documentation for ruby-debug-ide-0.6.1
Done installing documentation for ruby-debug-ide after 0 seconds
1 gem installed
$ gem install debase
Building native extensions. This could take a while...
Successfully installed debase-0.2.2
Parsing documentation for debase-0.2.2
Installing ri documentation for debase-0.2.2
Done installing …
```
> readme.md: Removed explicit gem versions

- src/debugger/main.ts
- src/locate/locate.js
- src/providers/intellisense.ts
This fix improves the ability to debug when running inside of containers and enhances the ability to debug installed gems that do not exist within the workspace root.
Right now I have a hack that will symlink my system installed gems path within my workspace under `tmp/bundle` which I then overlay with a gem cache volume, I then use that same path as my GEM_HOME within the container so that I am able to step into gems, this is required because currently all paths are blindly prefixed with the cwd/remoteRoot.
This change means that if the file exists under say ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0, it will leave the path alone and not perform the path prefixing upon converting to and from client/debugger paths. Then when running my container I can ensure the in container gems are …
> Only override paths when file actually exists within the cwd/remoteRoot

- .travis.yml
- package.json
- src/languageConfiguration.test.ts
- src/languageConfiguration.ts
- src/ruby.ts
--
Fix bug #257 where the word match includes leading colons. Include a test to demonstrate the desired behavior.
Thanks for considering this!
> Fix bug where word match includes colon

- src/format/RuboCop.ts
> Respect the bundler option when formatting.

- README.md
- Outline directions to enable rubocop formatting in two steps
- Group all settings changes into one example config
- Add config setting `"editor.formatOnSave": true`
The existing README instructions didn't work for me without setting `"editor.formatOnSave"` to true. I also updated the README to reflect that the `formatOnSaveTimeout` setting is now in VSCode.
> Improve Documentation on Rubocop

- src/locate/locate.js
Fixes #398
Not calling the callback caused a bug that meant that after a few tasks
were enqueued on the parseQueue (i.e. a few change-/create-events), all
incoming tasks were queued and never executed. That lead to newly added
symbols not being added to the symbols list and the locations of all
symbols after that being off.
> Call the async-callback to clear parseQueue of items

- README.md
This PR adds mention of endwise as a supplementary tool for cleverly inserting `end` into the document. Not sure if formatting is the right section, but I thought it the most appropriate.
> Add endwise to README.md

- src/format/RuboCop.ts
TL;DR: `src/format/RuboCop.ts` should use `ruby.pathToBundler` configuration when specified.
Since I'm new to vscode extension development, I didn't understand how to add / run tests for vscode extensions. Thanks in advance if anyone helps to improve this PR. 
----
- `vscode-ruby` version: 0.20.0
- Ruby version: default 2.4.3, workspace 2.5.1
- Ruby version manager (if any): rvm
- VS Code version: 1.29.1
- Operating System: MacOS High Sierra (10.13.6)
- Using language server? no
Use `bundler` to run `AutoCorrect.test()` by `RubyDocumentFormattingEditProvider` from `ruby.pathToBundler` when `ruby.useBundler` is true and `ruby.pathToBundler` is specified.
It uses `bundle` from the default path.
I'm using rvm for ruby version control, and my default version and worksapce version is …
> Respect ruby.pathToBundler for RuboCop executable

- src/lint/lintCollection.ts
Need to check whether the document provided to the linter is still the
same object as in previous runs. I.e. when closing and re-opening a file,
the document object changes, so the existing linter object won't see
updates to the content anymore.
Fixes #373.
> Fix linter offenses not updating after re-opening a file.

- README.md
The section was removed from the README a while ago.
> Remove TODO section from table of contents

- src/task/rake.ts
Previously, the globPattern used in rake.ts was failing to find Rakefiles if they were named `Rakefile, without the `.rb` extension. This fixes the globPattern so now it matches in that case.
This has the downside of also matching any filename that starts with `Rakefile`, e.g. `Rakefile2` or `Rakefileadsadadsad`, but I'm not sure of a great way to fix this without that downside.
If you select `Task: Run Task` in the Command Palette you can see the difference (note the workspace needs to have a file named `Rakefile`, `Rakefile.rb` will be detected without this change).
Before:
After:
This fixes #273.
> Fix automatic Rake task detection.

- .vscode/extensions.json
eg2.tslint has been deprecated in favour of Microsoft's
`ms-vscode-vscode-typescript-tslint-pugin`
> Update extension recommendations

- README.md
This wasn't obvious to me, so I thought it would help others.
Would a screenshot be welcome?
> README update for viewing language server output

- src/lint/lib/linters/reek.js
Force excluding files specified in the configuration `exclude_paths` even if they are explicitly passed as arguments.
Resolves problem with exclude_paths in the `.reek` config being ignored since we run reek on single files rather than the whole project.
Example that now works after this PR.
```yaml
exclude_paths:
- db/migrate
```
> add --force-exclusion flag to reek options

- client/src/WorkspaceRubyEnvironment.ts
- client/src/extension.ts
- package-lock.json
- server/src/index.ts
- server/src/util/rebuilder.ts
Fix https://github.com/microsoft/vscode-remote-release/issues/153. 
VS Code released [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) recently, which allows users to connect VS Code to an isolated remote environment, e.g., ssh box, container or WSL. As remote environment is using Nodejs instead of Electron patched Nodejs, current prebuilt tree sitter binaries won't work properly.
To fix this issue 
* This PR added check for host environment and fetch corresponding prebuilt binaries based on both platform/arch and Node runtime
* `tree-sitter-node` already has prebuilt for Node so we want to do the same thing for `tree-sitter-ruby`, here is the PR for it https://github.com/tree-sitter/tree-sitter-ruby/pull/106
> Node Runtime

- client/src/util/env.ts
The LANG env variable is needed for rufo, so that it is able to parse ruby files with multibyte characters.
Since it should be available and correct in most Mac and Linux environments we only need to pass the host value.
I tested it and this resolves #493 for me.
> Pass LANG environment variable to language server

- README.md
The `"lint": true` flag on the rubocop configuration for linting runs the rubocop command with the `-l` flag. The rubocop documentation describes this flag with "Run only lint cops". However, the readme here describes the configuration as "enable all lint cops". This discrepancy led myself and some of my co-workers to believe that this configuration was required to enable any lint checks at all, and we were confused as to why many checks were not being performed with this config option set to true. This pr updates the description of the configuration to be more in line with the rubocop documentation.
> Clarify rubocop configuration for 'lint: true'

- src/debugger/main.ts
Allow case insensitive path comparison on Windows.
Fixes path generation when local is Windows and remote is Posix.
I had issue debugging a ruby application running in a Linux docker environment using visual studio code on Windows. The issue seems to have started with VSCode 1.30
It was caused by the drive letter part of the workspace directory being lower case while the letter drive part of a file being upper case, preventing the path conversion to happen.
While debugging I also noticed that on Posix, `path.join` wasn't converting backslashes to slashes, so I changed the join call to handle this case.
> Path manipulation using correct OS path class

- package.json
Add missing task definition for rake tasks. This allows some customization of auto-detected tasks (e.g never scan the task output). Without task definition VSCode shows 'Value is not accepted' error and ignores that task.
> Add rake task definition

- src/locate/locate.js
I encountered a bug where `absPath in this.tree` was false so `waitForParse` was assigned the value of `this.parse(absParse)`. However, `this.parse(absParse)` does not have a return value so I was getting `TypeError: Cannot read property 'then' of undefined at Locate.listInFile`.
> Fix bug in locate.js

- src/languageConfiguration.ts
Atom's [`decreaseIndentPattern`](https://github.com/atom/language-ruby/blob/d88a4cfb32876295ec5b090a2994957e62130f4a/settings/language-ruby.cson) handles cases like this:
```
@date = Date.today()
@name = "Test Name"
@data = {
id: 8,
foo: Foo.new(
id: 1,
phone_number: "412-555-7640"
),
bar: Bar.new(
id: 1,
name: "Valentine",
vin: "DF5S6HFG365HGDCVG",
status: :AVAILABLE
),
start_time: start_time.to_s,
end_time: end_time.to_s,
cost: 23.45,
rating: 3,
}
```
> Update `decreaseIndentPattern` to match Atom

- syntaxes/ruby.cson.json
Current Master Branch shows this for Block Parameters lists:
Minor modifications to the grammar allow block parameters to be highlighted more consistently:
Added two new scopes:
`variable.other.block.unused.ruby` (to denote arguments that will go unused by the block, I've also kept the `variable.other.constant.ruby` that was previously applied to these so the highlighting stays even in the interim; `meta.block.parameters.ruby` to flesh out the detail of the scope.
Much of the matching for this was borrowed and modified off of the preexisting `meta.function.method.with-arguments.ruby` > `variable.parameter.function.ruby` scopes.
> Improve/Fix Block Parameter highlighting

- syntaxes/ruby.cson.json
> Support multiline and keyword option YARD comments

- syntaxes/ruby.cson.json
Resolves https://github.com/rubyide/vscode-ruby/issues/540
the purely regex equivalent has been tested here https://regexr.com/4m699
The only difference is that two backslashes are required in json
> Improve method match

- packages/language-server-ruby/src/Linter.ts
Fixes #531.
The getLinter() function just passes on the linter config (if it's an object), or continues with an empty object if it's any other values. This leads to unexpected behavior when setting a specific linter to `false` in the config. I.e. the linter is not disabled, as one would expect, but an empty linter configuration is used.
This PR fixes the issue by explicitly filtering linter configs that are `false` before passing them on to getLinter().
> Bugfix: Filter out linters that are disabled in the configuration.

- packages/vscode-ruby-client/README.md
Add a reference to debug configuration documentation in the README of vscode-ruby-client package; it is used in "Overview" section of the VS Code extension page and I think a reference there are necessary to inform users.
> Add a reference to debug configuration doc

- packages/vscode-ruby-client/src/util/env.ts
- packages/vscode-ruby-common/src/environment.ts
It is an official Bundler env variable as demonstrated here:
https://bundler.io/v2.0/bundle_install.html
Resolves https://github.com/rubyide/vscode-ruby/issues/574
- I was not able to get the build to fully pass locally, even on master, despite following the development guide, because it says `UnhandledPromiseRejectionWarning: Error: no event 'initialized' received after 5000 ms`
- I was not able to get ESLint to run because it says `[Error - 10:55:25 AM] .eslintrc.json » ../.eslintrc.base.json: 	Configuration for rule "@typescript-eslint/array-type" is invalid: 	Value "array" should be object. `
- It appears that Prettier works fine
> Add BUNDLE_PATH to whitelisted env variables

- packages/vscode-ruby-client/package.json
- packages/vscode-ruby-debugger/src/interface.ts
- packages/vscode-ruby-debugger/src/ruby.ts
Add Unix domain socket support to the debugger.
Makes it possible to attach to running Ruby processes via a Unix domain socket.
At Stripe, we're using a forked version of this extension in order to securely attach to Ruby services running on development boxes via Unix domain sockets. We'd like to upstream the change. :) 
Let me know if you need any more information or if this PR needs any additional changes.
> Add Unix domain socket support to the debugger.

- packages/language-server-ruby/src/linters/Reek.ts
Passes an `--stdin-filename` argument to Reek when linting files.
This gives Reek context about the piped contents and supports using the [`directories` configuration](https://github.com/troessner/reek#working-with-rails). 
Caveat:
Because this change sends the absolute path to the file, the configuration in directories must be prefixed with `**` for it to work. e.g.
```yml
directories:
'**/app/controllers':
IrresponsibleModule:
enabled: false
```
> Add Stdin-filename arg to Reek linter

- packages/vscode-ruby-debugger/src/interface.ts
- packages/vscode-ruby-debugger/src/main.ts
Should fix #536.
A first implementation of the evaluateName property on debug variable. This enables the "Copy Value" and related features in the VS Code Debugger. evaluateName needs to be build differently based on what kind of variable we're dealing with.
> Provide evaluateName property, so variable values can be copied from debugger.

- packages/vscode-ruby-client/src/providers/configuration.ts
Adds a default configuration for debugging Minitest tests as per https://github.com/rubyide/vscode-ruby/issues/630
> Add default debug configuration for Minitest

- docs/linting.md
The standard config object example was not nested in `"ruby.lint"`.
> put standard config in ruby.lint keyspace

- packages/vscode-ruby/syntaxes/ruby.cson.json
- packages/vscode-ruby/test/methods.rb
Fix for #663 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After
</summary>
</details>
No more leaking scopes
Also added double splat operator.
> Fix highlighting of method parameters. Add support for multiline parameters. 

- packages/vscode-ruby/syntaxes/ruby.cson.json
- packages/vscode-ruby/test/syntax.rb
This is a fix for  #658 
First I just wanted to check that there is a start of line or space char before `do` keyword, but there is some weird cases where you can put `do` right after the method name without space:
```ruby
def +
yield "test"
end
self.+do |e|
e.upcase
end
```
I am pretty sure this will work for any of these methods: `+`, `-`, `*`, `/`, `^`, `%`, `&`, `|`
Blocks are rarely used with them and blocks without space between method name and `do` I think almost never.
So I am not sure what is better.
> Check for : @ and $ before 'do'

- packages/language-server-ruby/src/formatters/RuboCop.ts
- packages/language-server-ruby/src/formatters/Rufo.ts
- packages/language-server-ruby/src/formatters/Standard.ts
- packages/language-server-ruby/src/linters/Reek.ts
- packages/language-server-ruby/src/linters/RuboCop.ts
Closes #641 
*Description of change and why it was needed here*
Single quotes around the `documentPath.fsPath` is necessary to support file paths that include spaces.
> Wrap documentPath.fsPath in single quotes to support file paths with spaces

- packages/vscode-ruby/syntaxes/ruby.cson.json
- packages/vscode-ruby/test/yard.rb
Fix #560 
Changes:
- add separate rule for `@see` tag - first argument of this tag could be URL
- add separate rule for `@!attribute` and `@!macro` tags - in these tags name goes after brackets
- change end regex in rules - now you dont need to make indentations on dividing empty lines
- add numbers to parameter names in tags
- add numbers, trailing `?` and `!` to hash keys names in `@option` tag
- add additional scope to hash keys in @option tag `comment.line.hashkey.yard.ruby`
> fix: yard syntax

- packages/language-server-ruby/src/util/spawn.ts
- packages/vscode-ruby-debugger/src/main.ts
*Description of change and why it was needed here*
Fixes https://github.com/rubyide/vscode-ruby/issues/510 and https://github.com/rubyide/vscode-ruby/issues/657
This fixes a notorious bug that engineers at Stripe encounter daily: The debugger fails to attach because they have a breakpoint that is unset in a file.
Specifically, the situation occurs when VS Code has one file open that has _all_ unset breakpoints (e.g., there are no active breakpoints in the file). It turns out that VS Code sends out a `setBreakpoints` request with _no_ breakpoints for this file. In this case, the Ruby debug adapter's code would not send a response to this request, so VS Code would wait forever for a response that would never come.
I've updated the code to ensure that it always responds once to this sort of …
> fix: when a setBreakpoint request comes in, always respond only once

- packages/.eslintrc.base.json
- packages/language-server-ruby/src/Formatter.ts
- packages/language-server-ruby/src/SettingsCache.ts
- packages/language-server-ruby/src/formatters/BaseFormatter.ts
- packages/language-server-ruby/src/formatters/Prettier.ts
- packages/language-server-ruby/src/formatters/index.ts
- packages/vscode-ruby-client/README.md
- packages/vscode-ruby-client/package.json
Requested by https://github.com/rubyide/vscode-ruby/issues/681. [Prettier for ruby](https://github.com/prettier/plugin-ruby) has been released some weeks ago, would be nice if vscode-ruby can manage it !
> feat(prettier): add prettier management

- docs/linting.md
This was documented earlier, but was removed at some point
> Document the forceExclusion option

- .github/workflows/ci.yml
https://github.com/rubyide/vscode-ruby/runs/2107273120 fails with following message
```
Run actions/setup-ruby@v1
with:
ruby-version: 2.4
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.4 not found
```
So just tried to use it... 🤔
> Use ruby/setup-ruby instead of deprecated one

- packages/vscode-ruby/syntaxes/ruby.cson.json
When I'm digging a syntax highlight issue, found these typos. 😄
> Fix some typos

- packages/language-server-ruby/src/linters/Reek.ts
- packages/language-server-ruby/src/linters/RuboCop.ts
> Pass valid filenames to RuboCop and Reek

- docs/debugger.md
- packages/vscode-ruby-client/package.json
- packages/vscode-ruby-debugger/src/interface.ts
- packages/vscode-ruby-debugger/src/main.ts
- packages/vscode-ruby-debugger/src/ruby.ts
At Stripe, we use sorbet and other internal utilities that 'pollute' the stack - they create
a large number of frames that are not interesting to our developers when debugging. This commit
adds two features that help avoid those frames.
skipFiles was inspired by the corresponding js debugger feature. It's useful for avoiding
uninteresting frames that are between interesting frames (sorbet falls in to this category).
Skipped files do not appear in stack traces, an the debugger automatically steps through them.
finishFiles is useful for avoiding frames that define the top of a never-interesting call stack.
The debugger automatically steps out of them instead of through them.
showDebuggerCommands is like showDebuggerOutput, but in the other direction. I found it useful
when debugging both …
> feat: add skipFiles and showDebuggerCommands

- docs/linting.md
The current "RuboCop CLI args" link gives a 404.
> Replace broken RuboCop CLI args link in linting doc

- packages/vscode-ruby-client/package.json
The `forceExclusion` option was added in b5cb94b88dc514a484d82e439ae6090cf4a8ca2f but not added to the extension configuration. Therefore, VSCode did not suggest this property when editing the configuration.
> fix(rubocop): add `forceExclusion` to extension configuration

- docs/troubleshooting.md
The [troubleshooting](https://github.com/rubyide/vscode-ruby/blob/master/docs/troubleshooting.md) document says that linters are run from the workspace root:
> All commands are run with a cwd of the workspace root.
However, as reported in #717, linters are in fact *not* run from the workspace root.
[This comment](https://github.com/rubyide/vscode-ruby/issues/717#issuecomment-819798274) says that _not_ running from the workspace root is intentional. It allows people to put multiple linter configuration files in the project. We expect linters to look recursively up the directory tree to find their configuration file.
This means that the behavior is not a bug. The documentation is wrong.
This pull request fixes the documentation.
> docs: fix documentation about linter behavior

- docs/legacy.md
Based on the discussion in #599, if the comments from @wingrunr21 is still valid then I think this would help clarify the current situation.
> Clarify `rubyLocate` option in legacy docs

- packages/vscode-ruby/language-configuration-erb.json
This brings the same on-enter behavior from the HTML language package to ERB. Specifically, when the cursor is between a start and end tag, the editor inserts a new line, puts the cursor at the new indent, and moves the closing tag to the line below at the proper indent.
Currently ERB has this behavior:
After this change it works like this:
This is my first contribution here and I had problems running `yarn watch`. (There was an error with copying tree-sitter.wasm) However run and debug worked fine and I was able to test manually. I'm happy to add tests if someone can provide some direction.
> feat(erb): add HTML onEnterRules
