rubyide/vscode-ruby

.vscode/launch.json, src/interface.ts, src/main.ts, src/ruby.ts, src/typings/xmldom/xmldom.d.ts
There will be some js -> ts changes required.
=> Working debugger.

.travis.yml, appveyor.yml, src/interface.ts, src/main.ts, src/ruby.ts, src/typings/xmldom/xmldom.d.ts
As per last PR.
None of those errors cause failure.
I've reduced it to 4 'errors' by changing some of the signatures and defining types as `:any` in some cases. The remaining erros are:
```
src/ruby.ts(74,52): error TS2345: Argument of type 'string[]' is not assignable to parameter of type 'string'.
src/ruby.ts(153,22): error TS2339: Property 'includes' does not exist on type 'string'.
src/main.ts(239,34): error TS2346: Supplied parameters do not match any signature of call target.
src/main.ts(240,35): error TS2346: Supplied parameters do not match any signature of call target.
```
* The first one is because typescript doesn't think you can `concat` an array.
* The second one says `include` isn't a function …
=> Same PR, less 'errors'

.vscode/launch.json, package.json, src/interface.ts, src/ruby.ts
Substantial amount of tab to space changes. It seemed like you were part way through doing this.
=> Correct launch schema for usable settings

package.json, src/ruby.ts
Added functionality as discussed under issue #16.
=> Run under bundle, allow full paths

readme.md
=> Fix trivial Readme typo, it should be *nix, but not *inx

lint/lintProcess.js, ruby.js
@rebornix Some minor changes that will give a speed increase
=> Snippets and end highlight - tidy

package.json, readme.md, src/ruby.ts
=> Process env

package.json, ruby.js
Allow specification of full path to the Ruby interpreter and
rct-complete command for environments in which multiple versions
of Ruby and gems are installed.
=> Intellisense:  Allow specification of full paths.

locate/locate.js, package.json, readme.md, ruby.js
Initial goto definition provision. All ruby parsing done in Javascript! Have a codebase with >2600 files here: parses in 3.5 seconds!!
=> Goto defintions

format/RuboCop.js, lint/linters/RuboCop.js, lint/linters/ruby-lint.js, package.json, readme.md, ruby.js
=> Add formatting capability

package.json, snippets/erb.json
This adds erb snippets `if..else..end`, `if..end`, `else`, `end`, `unless..end`, `unless..else..end`, `items.each do`.
Support for common erb tag such as `<% %>`, `<%= %>`, `<%# %>`, `<% -%>` will be on different pull request. I'm planning to make a command for easy toggling that.
=> Add erb Snippets

lint/lintCollection.js, ruby.js
=> Fix case issue for required internals

ruby.js
=> Allow auto complete to run on '.' press

.jsbeautifyrc, CHANGELOG.md, format/RuboCop.js, lint/lib/linters/RuboCop.js, locate/locate.js, package.json, readme.md, ruby.js
Improves formatting support by using the correct config file (if found).
Add CHANGELOG.md
Add Formatters to VS Code categories.
=> Improve formatting

gulpfile.js
=> Update sourceRoot in gulpfile.js.

snippets/erb.json
Adds `<% %>` and `<%= %>` to ERB snippets
=> Add common ERB snippets

src/main.ts
*(Now with no undesired commits...)*
This PR enables the commented-out code in the debug adapter that supports conditional breakpoints.
Tested against SketchUp/sketchup-ruby-debugger#11 which allows conditional breakpoints to be set.
---
=> Enable conditional breakpoint support.

syntaxes/ruby.tmLanguage
Update Ruby syntax file to support Ruby 2.3 squiggly heredoc syntax.
Resolves #110
=> Fix squiggly heredoc syntax

readme.md
=> Typo - broght => brought

lint/lib/linters/RuboCop.js
Fixes https://github.com/rubyide/vscode-ruby/issues/175
=> Remove force exclusion for rubocop

.vscode/tasks.json
=> update tasks.json to 2.0

src/ruby.ts
* add private/protected keywords to increaseIndentPattern
* remove when keyword from decreaseIndentPattern
Fixes https://github.com/rubyide/vscode-ruby/issues/203
=> improve indentation

syntaxes/ruby.tmLanguage
=> Add "delegate" to special method keywords.

package.json
=> Added .arb to file extensions list

package.json
this allows easier editing from vs code's settings editor
=> set ruby.useBundler config option type to boolean

readme.md
=> Fixes broken anchor link in README

snippets/ruby.json
=> fix wrong placeholder in "if else" snippet

package.json
This PR changes the title from "ruby language settings" to "Ruby configuration".
=> Update settings panel title

snippets/ruby.json
Added a snippet for the case statement block
Signed-off-by: Salim Djerbouh <caddydz4@gmail.com>
*Description of change and why it was needed here*
=> added switch case statement snippet

packages/vscode-ruby/syntaxes/ruby.cson.json, packages/vscode-ruby/test/hash.rb
=> fix: hashkey with trailing ! or ?
